### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_cursor'

### ISSUE THREAD

**Issue by heyshakya** [CN-UPB/DeepCoMP#11]
After successfully executing all the commands
```
# only on ubuntu
sudo apt update
sudo apt upgrade
sudo apt install cmake build-essential zlib1g-dev python3-dev

# clone
git clone git@github.com:CN-UPB/DeepCoMP.git
cd DeepCoMP

# install all python dependencies
pip install .
# "python setup.py install" does not work for some reason: https://stackoverflow.com/a/66267232/2745116
# for development install (when changing code): pip install -e .

sudo apt install ffmpeg imagemagick
```
After that, I run this command to do a simulation
```
deepcomp --env medium --slow-ues 3 --alg ppo --agent central --workers 2 --train-steps 50000 --seed 42 --video both --result-dir /home/abhishek/cmc
```

My system is showing an error:
```
2022-04-18 15:20:33,524 WARNING deprecation.py:33 -- DeprecationWarning: `monitor` has been deprecated. Use `record_env` instead. This will raise an error in the future!

Traceback (most recent call last):
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2785, in _wait_cursor_for_draw_cm
    self.set_cursor(cursors.WAIT)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 468, in set_cursor
    self.canvas.get_property("window").set_cursor(cursord[cursor])
AttributeError: 'NoneType' object has no attribute 'set_cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abhishek/.local/bin/deepcomp", line 8, in <module>
    sys.exit(main())
  File "/home/abhishek/.local/lib/python3.8/site-packages/deepcomp/main.py", line 83, in main
    sim.run(render=args.video, log_dict=log_dict)
  File "/home/abhishek/.local/lib/python3.8/site-packages/deepcomp/util/simulation.py", line 700, in run
    zipped_results = Parallel(n_jobs=self.num_workers)(
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/home/abhishek/.local/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/abhishek/.local/lib/python3.8/site-packages/deepcomp/util/simulation.py", line 547, in run_episode
    self.save_animation(fig, patches, render)
  File "/home/abhishek/.local/lib/python3.8/site-packages/deepcomp/util/simulation.py", line 314, in save_animation
    html = anim.to_html5_video()
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 1332, in to_html5_video
    self.save(str(path), writer=writer)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 1152, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 384, in grab_frame
    self.fig.savefig(self._frame_sink(), format=self.frame_format,
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2098, in print_figure
    result = print_method(
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 447, in print_raw
    FigureCanvasAgg.draw(self)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 390, in draw
    with RendererAgg.lock, \
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2788, in _wait_cursor_for_draw_cm
    self.set_cursor(self._lastCursor)
  File "/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 468, in set_cursor
    self.canvas.get_property("window").set_cursor(cursord[cursor])
AttributeError: 'NoneType' object has no attribute 'set_cursor'
/home/abhishek/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py:195: Warning: Source ID 7 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)

```

My PC Configuration : OS = Ubuntu 20.04 LTS, HW = intel i5 8th Gen, 8 GB RAM

My pip status :
```
absl-py==1.0.0
aiohttp==3.8.1
aiohttp-cors==0.7.0
aioredis==2.0.1
aiosignal==1.2.0
alabaster==0.7.12
ale-py==0.7.4
apturl==0.5.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.1
astroid==2.9.1
astunparse==1.6.3
async-timeout==4.0.2
atari-py==0.2.9
attrs==21.4.0
AutoROM==0.4.2
AutoROM.accept-rom-license==0.4.2
Babel==2.9.1
backcall==0.2.0
bcrypt==3.1.7
bleach==3.1.1
blessings==1.7
blinker==1.4
box2d-py==2.3.8
Brlapi==0.7.0
cachetools==5.0.0
certifi==2019.11.28
cffi==1.15.0
chardet==3.0.4
charset-normalizer==2.0.9
chrome-gnome-shell==0.0.0
click==8.0.3
cloudpickle==1.2.2
colorama==0.4.3
colorful==0.5.4
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.28
dbus-python==1.2.16
debugpy==1.5.1
decorator==5.1.0
deepcomp @ file:///home/abhishek/cmc/DeepCoMP
defer==1.0.6
defusedxml==0.6.0
Deprecated==1.2.13
distlib==0.3.4
distro==1.4.0
distro-info===0.23ubuntu1
dm-tree==0.1.7
docutils==0.17.1
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.17.3
filelock==3.4.2
flatbuffers==2.0
frozenlist==1.3.0
future==0.18.2
gast==0.4.0
glfw==2.5.3
google-api-core==2.7.2
google-auth==2.6.5
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.56.0
gpustat==0.6.0
GPUtil==1.4.0
grpcio==1.44.0
gym==0.19.0
gym-notices==0.0.6
h5py==3.6.0
html5lib==1.0.1
httplib2==0.14.0
idna==2.8
imageio==2.16.2
imagesize==1.3.0
importlib-metadata==4.11.3
importlib-resources==5.4.0
ipykernel==5.2.0
ipython==7.30.1
ipython-genutils==0.2.0
ipywidgets==7.7.0
isort==5.10.1
jedi==0.18.1
Jinja2==3.0.3
joblib==0.16.0
jsonschema==4.3.3
jupyter==1.0.0
jupyter-client==7.1.0
jupyter-console==6.4.3
jupyter-core==4.9.1
jupyterlab-widgets==1.1.0
keras==2.7.0
Keras-Preprocessing==1.1.2
keyring==18.0.1
kiwisolver==1.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lazy-object-proxy==1.7.1
libclang==13.0.0
lockfile==0.12.2
logilab-common==1.4.3
louis==3.12.0
lz4==4.0.0
macaroonbakery==1.3.1
Mako==1.1.0
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.2.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
mock==3.0.5
monotonic==1.5
more-itertools==4.2.0
msgpack==1.0.3
mujoco-py==2.1.2.14
multidict==6.0.2
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.1.3
nest-asyncio==1.5.4
netifaces==0.10.4
notebook==6.4.10
numpy==1.19.5
numpydoc==0.7.0
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
olefile==0.46
opencensus==0.8.0
opencensus-context==0.1.2
opencv-python==4.5.5.64
opencv-python-headless==4.2.0.34
opt-einsum==3.3.0
pachi-py==0.0.21
packaging==21.3
pandas==1.4.2
pandocfilters==1.4.2
paramiko==2.6.0
parso==0.8.3
pathspec==0.9.0
pbr==5.4.5
pexpect==4.6.0
pickleshare==0.7.5
Pillow==9.1.0
platformdirs==2.4.1
pluggy==1.0.0
prometheus-client==0.14.1
prompt-toolkit==3.0.24
protobuf==3.20.0
psutil==5.5.1
ptyprocess==0.7.0
py-spy==0.3.11
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycodestyle==2.8.0
pycparser==2.21
pycups==1.9.73
pydantic==1.9.0
pyflakes==2.4.0
pygame==2.1.0
pyglet==1.3.2
Pygments==2.11.1
PyGObject==3.36.0
PyJWT==1.7.1
pylint==2.4.4
pymacaroons==0.13.0
PyNaCl==1.3.0
PyOpenGL==3.1.6
pyparsing==2.4.6
PyQt5==5.14.0
PyQt5-sip==12.9.0
PyQt6==6.2.2
PyQt6-Qt6==6.2.2
PyQt6-sip==13.2.0
pyRFC3339==1.1
pyrsistent==0.18.0
pysvn==1.9.9
python-apt==2.0.0+ubuntu0.20.4.7
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.3.3
python-slugify==5.0.2
pytz==2022.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==22.3.0
QtAwesome==0.4.4
qtconsole==4.6.0
QtPy==2.0.0
ray==1.4.0
redis==4.2.2
reportlab==3.5.34
requests==2.26.0
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
roman==2.0.0
rope==0.22.0
rsa==4.8
scipy==1.4.1
seaborn==0.10.1
SecretStorage==2.3.1
Send2Trash==1.8.0
Shapely==1.7.0
simplejson==3.16.0
sip==4.19.21
six==1.14.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
Sphinx==4.3.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spyder==3.3.6
spyder-kernels==0.5.2
structlog==21.5.0
structlog-round==1.0
svgpath2mpl==1.0.0
systemd-python==234
tabulate==0.8.9
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5
tensorflow==2.7.1
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.24.0
termcolor==1.1.0
terminado==0.13.3
testpath==0.5.0
text-unidecode==1.3
Theano==1.0.5
tinycss2==1.1.1
toml==0.10.2
tomli==1.2.3
tornado==6.1
tqdm==4.47.0
traitlets==5.1.1
typing_extensions==4.0.1
ubuntu-advantage-tools==27.7
ubuntu-drivers-common==0.0.0
ufw==0.36
ujson==5.1.0
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
virtualenv==20.12.1
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.1
widgetsnbextension==3.6.0
wrapt==1.13.3
wurlitzer==3.0.2
xdot==1.1
xkit==0.0.0
yapf==0.32.0
yarl==1.7.2
zipp==3.7.0

```

Please try to resolve this issue.
Any help would be appreciated.

Thanks in advance.

**Comment by stefanbschneider** [comment]
Thanks for opening the issue, I'll have a look as soon as possible and will come back to you.

**Comment by heyshakya** [comment]
Bug Fixed.
Use Updated Version of Matplotlib.
